In [ ]:
b=[1,2,3,4]
len(b)
print (type(b))

<class 'list'>


In [ ]:
import numpy as np
print (np.__version__)

a=np.array([1,2,4,4])
type(a)
print(a.size)
print(a.shape)


1.18.5
4
(4,)


Call np. count_nonzero(array == value, axis=n) with n as 1 to count the occurrences of value in each row. Define n as 0 to count the occurrences of value in each column.

In [ ]:
print (len(a))
print("how many 4s?",np.count_nonzero(a==4,axis=0))
a[3]=5
print (a)

4
how many 4s? 2
[1 2 4 5]


Shape of the array can be modified, array can be easily transposed

In [ ]:
a.shape=(2,2)
print(a)
print(a.T)
print (round(np.linalg.det(a)))
print (np.linalg.det(a.T))


[[1 2]
 [4 5]]
[[1 4]
 [2 5]]
-3.0
-2.9999999999999996


In [ ]:
a.shape=(4)
print (a)

[1 2 4 5]


In [ ]:
a.shape=(1,4)


In [ ]:
a.T.shape
a

array([[1, 2, 4, 5]])

## more functions
Here are some functions that are included in numpy arrays
like mean, median, variance and std deviation.


In [ ]:
a=np.array([1,3,4,6,3,6,7,8,9,0,6,5,74,3,24,26,4,68,42,1,2,5,9])
print ("Mean:{}, Std Dev:{}, Median:{}, Variance:{}".format(a.mean(),a.std(),np.median(a),a.var()))
print ("A:",np.sort(a))


Mean:13.73913043478261, Std Dev:20.078579092512776, Median:6.0, Variance:403.1493383742911
A: [ 0  1  1  2  3  3  3  4  4  5  5  6  6  6  7  8  9  9 24 26 42 68 74]


# Array selection through boolean arrays

In [ ]:
a=np.array([1,3,4,0,6,3,1])
boolarr=a>1
print(boolarr)
print (a[boolarr])
#or in a quicker way
print (a[(a<6)&(a>1)])

[False  True  True False  True  True False]
[3 4 6 3]
[3 4 3]


In [ ]:
#now with WHERE we can find the index of the array that satisfy a certain condition
index=np.where(a>1)
list(index[0])

print (a[list(index[0])]) #similar to the previous result
#how to multiply by 3 only the elements >3 ?
index=np.where(a>3)
for _ in index:
  a[_]*=3
print (a)
print (type(index))
print (index)


[  3 108 162   3]
[  1   3 324   0 486   3   1]
<class 'tuple'>
[2 4]


In [ ]:
#or in a simpler way:
a=np.array([1,3,4,0,6,3,1])
a[a>3]*=3
print (a)
print (a.size)

[ 1  3 12  0 18  3  1]
7


### Generate a random array

In [ ]:
ran=np.random.randint(0,10,100,int)

In [ ]:
print(ran)

[5 5 5 9 3 7 0 0 0 5 9 3 7 6 5 7 7 0 3 3 0 1 5 1 9 6 8 7 6 6 3 8 7 7 9 2 2
 0 1 7 5 1 5 6 6 8 1 0 3 7 8 2 9 0 7 0 1 3 3 6 4 5 5 4 2 8 4 9 9 3 2 3 7 0
 7 8 5 5 2 3 8 7 9 9 3 3 4 7 7 7 6 3 5 0 0 3 8 0 8 5]


In [ ]:
vec=np.arange(15,56,1)
print (vec)

[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]


In [ ]:
print (vec[1:-8])

[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47]


In [ ]:
print(vec.T)

[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]


In [ ]:
print (vec)

[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]


# Playing with matrices 
[https://www.mathsisfun.com/algebra/matrix-introduction.html]

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
ran=np.random.randint(0,5,(3,3),int)
print(ran)
print (round(np.linalg.det(ran)))

[[0 3 1]
 [2 4 4]
 [2 3 0]]
22.0


In [ ]:
import numpy as np
arr1=np.array([1,3,4,5,6])
arr2=np.array([2,1,0,0,2])
arr3=np.multiply(arr1,arr2)
print(arr3)


[ 2  3  0  0 12]


In [ ]:
mat=np.array([[1,2],[3,5]])
print ("matrix:\n",mat)
print ("matrix transposed\n",mat.T)
print (np.linalg.inv(mat))

matrix:
 [[1 2]
 [3 5]]
matrix transposed
 [[1 3]
 [2 5]]
[[-5.  2.]
 [ 3. -1.]]


In [ ]:
mat3=np.dot(mat,np.linalg.inv(mat))
#following lines are weird but useful if you don't want to see exponential negative numbers instead of 0
eps=0.0000001
mat3[np.abs(mat3) < eps] = 0

print (mat3)


[[1. 0.]
 [0. 1.]]


In [ ]:
import numpy as np
print (np.__version__)
a=np.array([[1,2],[3,4]])
print (a)
print (a.T)

1.18.5
[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [ ]:
b=a.dot(a.T)
print (b)

[[ 5 11]
 [11 25]]


In [ ]:
print (np.linalg.inv(b))
print (np.dot(np.linalg.pinv(a),a.T))

[[ 6.25 -2.75]
 [-2.75  1.25]]
[[-4.4408921e-16 -2.0000000e+00]
 [ 5.0000000e-01  2.5000000e+00]]
